### ISSUE TITLE
Debugging does not work

### ISSUE THREAD

**Issue by sebakerckhof** [electron-userland/electron-prebuilt-compile#23] opened 2017-01-16 16:46 UTC
Using normal `electron-prebuilt` I can debug apps using the way described here:
https://github.com/electron/electron/blob/master/docs/tutorial/debugging-main-process.md

So like `electron --debug-brk=5858 test/index.js`

If I replace `electron prebuilt` with `electron-prebuilt-compile`, the same command gives me:
```
/home/seke/dev/purple/app/node_modules/.bin/electron --debug-brk=5858 --nolazy test/index.js 
App threw an error during load
Error: Cannot find module '/home/seke/dev/purple/app/--debug-brk=5858'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/home/seke/dev/purple/app/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at init (/home/seke/dev/purple/app/node_modules/electron-compile/lib/config-parser.js:279:16)
    at main (/home/seke/dev/purple/app/node_modules/electron-prebuilt-compile/lib/es6-init.js:38:29)
    at Object.<anonymous> (/home/seke/dev/purple/app/node_modules/electron-prebuilt-compile/lib/es6-init.js:41:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
```

**Comment by soitech** [comment] 2017-02-28 19:19
+1 using electron-forge with my project broke debugging in Webstorm.

**Comment by paulcbetts** [comment] 2017-03-04 06:39
We probably have to special-case those paths, hm

**Comment by jacobq** [comment] 2017-03-15 22:11
I'm trying to figure out https://github.com/felixrieseberg/ember-electron/issues/175 which seems to be related to this as well (`ember-electron` is transitioning to using `electron-forge` for packaging in v2.0).

It looks to me like what's breaking some of my existing code is that `__dirname` no longer points to my app's dist folder but rather to something like `<app>/node_modules/electron-prebuilt-compile/node_modules/electron/dist/resources/electron.asar/renderer`. [`reset-search-paths.js`](https://github.com/electron/electron/blob/v1.6.3/lib/common/reset-search-paths.js) causes the node module search algorithm to only walk up directories from `<app>/node_modules/electron-prebuilt-compile/node_modules/electron/dist/resources/electron.asar/renderer/init.js` and to stop when it hits the resources directory. Since the `node_modules` I want to access are in `<app>/node_modules`, attempting to `require` them without specifying an explicit path causes a `Cannot find module` error to occur.

One can work around this by specifying paths to modules, but this gets rather messy quickly. As a quick & dirty work-around, I ended up defeating the search path protection by putting entries back into `globalPaths`, but I feel like there should be a way to get these modules without "cheating" like that.

Could anyone help me understand the way this was intended to be done?

**Comment by Hum4n01d** [comment] 2017-04-13 18:03
OMG I finally figured out that this was the problem behind my app not debugging in neither VSCode **nor** PyCharm!! Please fix this! @paulcbetts

**Comment by paulcbetts** [comment] 2017-04-13 18:19
@jacobq reset-search-paths is part of Electron proper, not part of prebuilt-compile

**Comment by jacobq** [comment] 2017-04-13 19:04
@paulcbetts Right, but I believe it gets a different "starting point" (root module? forgive my ignorance of the proper term) when running with `electron-prebuilt-compile` for some reason. The problem I was having has been solved now though, so I haven't given this further thought.

**Comment by Hum4n01d** [comment] 2017-04-13 20:45
The problem is here: https://github.com/electron-userland/electron-prebuilt-compile/blob/master/src/cli.js#L6. The cli arguments aren't being interpreted properly. This is causing `electron-prebuilt-compile` to try and run the app `/path/to/electron/app/--debug-brk=5858` which is not a valid directory let alone an electron app. 

Flags need to be parsed separately from arguments

**Comment by MarshallOfSound** [comment] 2017-04-16 12:24
Of note to people in this issue, there's a PR up to expose an entrypoint in forge for super easy debugging through VSCode

https://github.com/electron-userland/electron-forge/pull/198

**Comment by paulcbetts** [comment] 2017-04-16 18:31
electron-forge is a good place to fix this, closing here

**Closed by paulcbetts** 2017-04-16 18:31 UTC
